### ISSUE TITLE
No Farm_Combat file

### ISSUE THREAD

**Issue by Laserine** [lambui/StardewValleyMod_OmniFarm#4]
To enable the mod, i need Farm_Combat.xnb , which i dont have.
Is it hidden, not there or am i just stupid?
Ive seen people use the mod, so it cant be that someone forgot to add it.

**Comment by lambui** [comment]
Maybe you are just stupid. Just kidding. Yeah, that's my bad.
I am assuming that you get the latest release (OmniFarm v.2.0.3). It seems like it doesn't have the xnb inside. I forget to add it.
What you can do is download an earlier version (OmniFarm v.2.0.2) and get the xnb file in there. Then you would want to put that xnb in the assets folder within folder of the new version.
Another thing is that you need to make sure to set the useOptionalCave to false in the config file if you don't have any custom FarmCave.xnb inside the assets folder.
[Farm_Combat.zip](https://github.com/lambui/StardewValleyMod_OmniFarm/files/2109216/Farm_Combat.zip)

**Comment by Laserine** [comment]
Thank you very much!
Everything works now.

**Comment by lambui** [comment]
Nice!
